import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import ItWorks from '../components/ItWorks'
import Upcoming from '../components/Upcoming'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Meet Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <ItWorks/>
      <Upcoming/>
      

      
    </div>
  )
}
